### PR TITLE
Create es.js

### PR DESCRIPTION
**Pull request by bitcod3r**
Translation to spanish

### CODE REVIEW

**Comment by vsn4ik** [comment]
Thanks!

**Comment by bitcod3r** [comment]
I need to correcto something in http://vsn4ik.github.io/bootstrap-checkbox/. How could I do it? A new pull request?

**Comment by vsn4ik** [comment]
Yes. The same you can open new issue or add a comment to the line of file with "code".

**Comment by bitcod3r** [comment]
Thank you. Already found the way ;)

**Pull request merged**
